// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/control/controlpb/control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED         MessageType = 0
	MessageType_MESSAGE_TYPE_AUTH_REQUEST        MessageType = 1
	MessageType_MESSAGE_TYPE_AUTH_RESPONSE       MessageType = 2
	MessageType_MESSAGE_TYPE_HEARTBEAT           MessageType = 3
	MessageType_MESSAGE_TYPE_OPEN_STREAM         MessageType = 4
	MessageType_MESSAGE_TYPE_PROXY_SNAPSHOT      MessageType = 5
	MessageType_MESSAGE_TYPE_PROXY_LIST_REQUEST  MessageType = 6
	MessageType_MESSAGE_TYPE_PROXY_LIST_RESPONSE MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_AUTH_REQUEST",
		2: "MESSAGE_TYPE_AUTH_RESPONSE",
		3: "MESSAGE_TYPE_HEARTBEAT",
		4: "MESSAGE_TYPE_OPEN_STREAM",
		5: "MESSAGE_TYPE_PROXY_SNAPSHOT",
		6: "MESSAGE_TYPE_PROXY_LIST_REQUEST",
		7: "MESSAGE_TYPE_PROXY_LIST_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":         0,
		"MESSAGE_TYPE_AUTH_REQUEST":        1,
		"MESSAGE_TYPE_AUTH_RESPONSE":       2,
		"MESSAGE_TYPE_HEARTBEAT":           3,
		"MESSAGE_TYPE_OPEN_STREAM":         4,
		"MESSAGE_TYPE_PROXY_SNAPSHOT":      5,
		"MESSAGE_TYPE_PROXY_LIST_REQUEST":  6,
		"MESSAGE_TYPE_PROXY_LIST_RESPONSE": 7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_control_controlpb_control_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_control_controlpb_control_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{0}
}

type MuxFrameType int32

const (
	MuxFrameType_MUX_FRAME_TYPE_UNSPECIFIED MuxFrameType = 0
	MuxFrameType_MUX_FRAME_TYPE_OPEN        MuxFrameType = 1
	MuxFrameType_MUX_FRAME_TYPE_DATA        MuxFrameType = 2
	MuxFrameType_MUX_FRAME_TYPE_CLOSE       MuxFrameType = 3
	MuxFrameType_MUX_FRAME_TYPE_RESET       MuxFrameType = 4
)

// Enum value maps for MuxFrameType.
var (
	MuxFrameType_name = map[int32]string{
		0: "MUX_FRAME_TYPE_UNSPECIFIED",
		1: "MUX_FRAME_TYPE_OPEN",
		2: "MUX_FRAME_TYPE_DATA",
		3: "MUX_FRAME_TYPE_CLOSE",
		4: "MUX_FRAME_TYPE_RESET",
	}
	MuxFrameType_value = map[string]int32{
		"MUX_FRAME_TYPE_UNSPECIFIED": 0,
		"MUX_FRAME_TYPE_OPEN":        1,
		"MUX_FRAME_TYPE_DATA":        2,
		"MUX_FRAME_TYPE_CLOSE":       3,
		"MUX_FRAME_TYPE_RESET":       4,
	}
)

func (x MuxFrameType) Enum() *MuxFrameType {
	p := new(MuxFrameType)
	*p = x
	return p
}

func (x MuxFrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MuxFrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_control_controlpb_control_proto_enumTypes[1].Descriptor()
}

func (MuxFrameType) Type() protoreflect.EnumType {
	return &file_internal_control_controlpb_control_proto_enumTypes[1]
}

func (x MuxFrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MuxFrameType.Descriptor instead.
func (MuxFrameType) EnumDescriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{1}
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=goginx.control.v1.MessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_internal_control_controlpb_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_controlpb_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AuthRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientId          string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Credential        string                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	Nonce             string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,4,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Version           string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Protocols         []string               `protobuf:"bytes,6,rep,name=protocols,proto3" json:"protocols,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_internal_control_controlpb_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_controlpb_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *AuthRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *AuthRequest) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *AuthRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AuthRequest) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

type AuthResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Accepted               bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	SessionId              string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SelectedProtocol       string                 `protobuf:"bytes,3,opt,name=selected_protocol,json=selectedProtocol,proto3" json:"selected_protocol,omitempty"`
	HeartbeatIntervalNanos int64                  `protobuf:"varint,4,opt,name=heartbeat_interval_nanos,json=heartbeatIntervalNanos,proto3" json:"heartbeat_interval_nanos,omitempty"`
	ConfigVersion          int64                  `protobuf:"varint,5,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Reason                 string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_internal_control_controlpb_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_controlpb_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AuthResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthResponse) GetSelectedProtocol() string {
	if x != nil {
		return x.SelectedProtocol
	}
	return ""
}

func (x *AuthResponse) GetHeartbeatIntervalNanos() int64 {
	if x != nil {
		return x.HeartbeatIntervalNanos
	}
	return 0
}

func (x *AuthResponse) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *AuthResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Heartbeat struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientId           string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ObservedAtUnixNano int64                  `protobuf:"varint,3,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	ConfigVersion      int64                  `protobuf:"varint,4,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	ActiveProxies      int32                  `protobuf:"varint,5,opt,name=active_proxies,json=activeProxies,proto3" json:"active_proxies,omitempty"`
	ActiveStreams      int32                  `protobuf:"varint,6,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	UploadBytes        int64                  `protobuf:"varint,7,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	DownloadBytes      int64                  `protobuf:"varint,8,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	ErrorSummary       string                 `protobuf:"bytes,9,opt,name=error_summary,json=errorSummary,proto3" json:"error_summary,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_control_controlpb_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_controlpb_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Heartbeat) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Heartbeat) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

func (x *Heartbeat) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Heartbeat) GetActiveProxies() int32 {
	if x != nil {
		return x.ActiveProxies
	}
	return 0
}

func (x *Heartbeat) GetActiveStreams() int32 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *Heartbeat) GetUploadBytes() int64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *Heartbeat) GetDownloadBytes() int64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

func (x *Heartbeat) GetErrorSummary() string {
	if x != nil {
		return x.ErrorSummary
	}
	return ""
}

type ProxySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Proxies       []*Proxy               `protobuf:"bytes,2,rep,name=proxies,proto3" json:"proxies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxySnapshot) Reset() {
	*x = ProxySnapshot{}
	mi := &file_internal_control_controlpb_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxySnapshot) ProtoMessage() {}

func (x *ProxySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_controlpb_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxySnapshot.ProtoReflect.Descriptor instead.
func (*ProxySnapshot) Descriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{4}
}

func (x *ProxySnapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProxySnapshot) GetProxies() []*Proxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

type Proxy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientId          string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type              string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	EntryHost         string                 `protobuf:"bytes,7,opt,name=entry_host,json=entryHost,proto3" json:"entry_host,omitempty"`
	EntryPort         int32                  `protobuf:"varint,8,opt,name=entry_port,json=entryPort,proto3" json:"entry_port,omitempty"`
	TargetHost        string                 `protobuf:"bytes,9,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort        int32                  `protobuf:"varint,10,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Description       string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAtUnixNano int64                  `protobuf:"varint,12,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	UpdatedAtUnixNano int64                  `protobuf:"varint,13,opt,name=updated_at_unix_nano,json=updatedAtUnixNano,proto3" json:"updated_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	mi := &file_internal_control_controlpb_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_controlpb_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{5}
}

func (x *Proxy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Proxy) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Proxy) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Proxy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Proxy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Proxy) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Proxy) GetEntryHost() string {
	if x != nil {
		return x.EntryHost
	}
	return ""
}

func (x *Proxy) GetEntryPort() int32 {
	if x != nil {
		return x.EntryPort
	}
	return 0
}

func (x *Proxy) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *Proxy) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *Proxy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Proxy) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

func (x *Proxy) GetUpdatedAtUnixNano() int64 {
	if x != nil {
		return x.UpdatedAtUnixNano
	}
	return 0
}

type OpenStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ProxyId       string                 `protobuf:"bytes,2,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	TargetHost    string                 `protobuf:"bytes,4,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort    int32                  `protobuf:"varint,5,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStream) Reset() {
	*x = OpenStream{}
	mi := &file_internal_control_controlpb_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStream) ProtoMessage() {}

func (x *OpenStream) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_controlpb_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStream.ProtoReflect.Descriptor instead.
func (*OpenStream) Descriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{6}
}

func (x *OpenStream) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OpenStream) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *OpenStream) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *OpenStream) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *OpenStream) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

type ProxyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion int64                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyListRequest) Reset() {
	*x = ProxyListRequest{}
	mi := &file_internal_control_controlpb_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyListRequest) ProtoMessage() {}

func (x *ProxyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_controlpb_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyListRequest.ProtoReflect.Descriptor instead.
func (*ProxyListRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{7}
}

func (x *ProxyListRequest) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

type ProxyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Proxies       []*Proxy               `protobuf:"bytes,2,rep,name=proxies,proto3" json:"proxies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyListResponse) Reset() {
	*x = ProxyListResponse{}
	mi := &file_internal_control_controlpb_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyListResponse) ProtoMessage() {}

func (x *ProxyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_controlpb_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyListResponse.ProtoReflect.Descriptor instead.
func (*ProxyListResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{8}
}

func (x *ProxyListResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProxyListResponse) GetProxies() []*Proxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

type MuxFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Type          MuxFrameType           `protobuf:"varint,2,opt,name=type,proto3,enum=goginx.control.v1.MuxFrameType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuxFrame) Reset() {
	*x = MuxFrame{}
	mi := &file_internal_control_controlpb_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuxFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuxFrame) ProtoMessage() {}

func (x *MuxFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_controlpb_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuxFrame.ProtoReflect.Descriptor instead.
func (*MuxFrame) Descriptor() ([]byte, []int) {
	return file_internal_control_controlpb_control_proto_rawDescGZIP(), []int{9}
}

func (x *MuxFrame) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *MuxFrame) GetType() MuxFrameType {
	if x != nil {
		return x.Type
	}
	return MuxFrameType_MUX_FRAME_TYPE_UNSPECIFIED
}

func (x *MuxFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MuxFrame) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_internal_control_controlpb_control_proto protoreflect.FileDescriptor

const file_internal_control_controlpb_control_proto_rawDesc = "" +
	"\n" +
	"(internal/control/controlpb/control.proto\x12\x11goginx.control.v1\"X\n" +
	"\bEnvelope\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.goginx.control.v1.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xc8\x01\n" +
	"\vAuthRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12.\n" +
	"\x13timestamp_unix_nano\x18\x04 \x01(\x03R\x11timestampUnixNano\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1c\n" +
	"\tprotocols\x18\x06 \x03(\tR\tprotocols\"\xef\x01\n" +
	"\fAuthResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12+\n" +
	"\x11selected_protocol\x18\x03 \x01(\tR\x10selectedProtocol\x128\n" +
	"\x18heartbeat_interval_nanos\x18\x04 \x01(\x03R\x16heartbeatIntervalNanos\x12%\n" +
	"\x0econfig_version\x18\x05 \x01(\x03R\rconfigVersion\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\xde\x02\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x121\n" +
	"\x15observed_at_unix_nano\x18\x03 \x01(\x03R\x12observedAtUnixNano\x12%\n" +
	"\x0econfig_version\x18\x04 \x01(\x03R\rconfigVersion\x12%\n" +
	"\x0eactive_proxies\x18\x05 \x01(\x05R\ractiveProxies\x12%\n" +
	"\x0eactive_streams\x18\x06 \x01(\x05R\ractiveStreams\x12!\n" +
	"\fupload_bytes\x18\a \x01(\x03R\vuploadBytes\x12%\n" +
	"\x0edownload_bytes\x18\b \x01(\x03R\rdownloadBytes\x12#\n" +
	"\rerror_summary\x18\t \x01(\tR\ferrorSummary\"]\n" +
	"\rProxySnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x122\n" +
	"\aproxies\x18\x02 \x03(\v2\x18.goginx.control.v1.ProxyR\aproxies\"\x91\x03\n" +
	"\x05Proxy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"entry_host\x18\a \x01(\tR\tentryHost\x12\x1d\n" +
	"\n" +
	"entry_port\x18\b \x01(\x05R\tentryPort\x12\x1f\n" +
	"\vtarget_host\x18\t \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\n" +
	" \x01(\x05R\n" +
	"targetPort\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12/\n" +
	"\x14created_at_unix_nano\x18\f \x01(\x03R\x11createdAtUnixNano\x12/\n" +
	"\x14updated_at_unix_nano\x18\r \x01(\x03R\x11updatedAtUnixNano\"\xa2\x01\n" +
	"\n" +
	"OpenStream\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x19\n" +
	"\bproxy_id\x18\x02 \x01(\tR\aproxyId\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vtarget_host\x18\x04 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x05 \x01(\x05R\n" +
	"targetPort\"9\n" +
	"\x10ProxyListRequest\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x03R\rconfigVersion\"a\n" +
	"\x11ProxyListResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x122\n" +
	"\aproxies\x18\x02 \x03(\v2\x18.goginx.control.v1.ProxyR\aproxies\"\x8e\x01\n" +
	"\bMuxFrame\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.goginx.control.v1.MuxFrameTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason*\x90\x02\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MESSAGE_TYPE_AUTH_REQUEST\x10\x01\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_AUTH_RESPONSE\x10\x02\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HEARTBEAT\x10\x03\x12\x1c\n" +
	"\x18MESSAGE_TYPE_OPEN_STREAM\x10\x04\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_PROXY_SNAPSHOT\x10\x05\x12#\n" +
	"\x1fMESSAGE_TYPE_PROXY_LIST_REQUEST\x10\x06\x12$\n" +
	" MESSAGE_TYPE_PROXY_LIST_RESPONSE\x10\a*\x94\x01\n" +
	"\fMuxFrameType\x12\x1e\n" +
	"\x1aMUX_FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MUX_FRAME_TYPE_OPEN\x10\x01\x12\x17\n" +
	"\x13MUX_FRAME_TYPE_DATA\x10\x02\x12\x18\n" +
	"\x14MUX_FRAME_TYPE_CLOSE\x10\x03\x12\x18\n" +
	"\x14MUX_FRAME_TYPE_RESET\x10\x04B:Z8github.com/simp-frp/go-ginx-2/internal/control/controlpbb\x06proto3"

var (
	file_internal_control_controlpb_control_proto_rawDescOnce sync.Once
	file_internal_control_controlpb_control_proto_rawDescData []byte
)

func file_internal_control_controlpb_control_proto_rawDescGZIP() []byte {
	file_internal_control_controlpb_control_proto_rawDescOnce.Do(func() {
		file_internal_control_controlpb_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_control_controlpb_control_proto_rawDesc), len(file_internal_control_controlpb_control_proto_rawDesc)))
	})
	return file_internal_control_controlpb_control_proto_rawDescData
}

var file_internal_control_controlpb_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_control_controlpb_control_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_control_controlpb_control_proto_goTypes = []any{
	(MessageType)(0),          // 0: goginx.control.v1.MessageType
	(MuxFrameType)(0),         // 1: goginx.control.v1.MuxFrameType
	(*Envelope)(nil),          // 2: goginx.control.v1.Envelope
	(*AuthRequest)(nil),       // 3: goginx.control.v1.AuthRequest
	(*AuthResponse)(nil),      // 4: goginx.control.v1.AuthResponse
	(*Heartbeat)(nil),         // 5: goginx.control.v1.Heartbeat
	(*ProxySnapshot)(nil),     // 6: goginx.control.v1.ProxySnapshot
	(*Proxy)(nil),             // 7: goginx.control.v1.Proxy
	(*OpenStream)(nil),        // 8: goginx.control.v1.OpenStream
	(*ProxyListRequest)(nil),  // 9: goginx.control.v1.ProxyListRequest
	(*ProxyListResponse)(nil), // 10: goginx.control.v1.ProxyListResponse
	(*MuxFrame)(nil),          // 11: goginx.control.v1.MuxFrame
}
var file_internal_control_controlpb_control_proto_depIdxs = []int32{
	0, // 0: goginx.control.v1.Envelope.type:type_name -> goginx.control.v1.MessageType
	7, // 1: goginx.control.v1.ProxySnapshot.proxies:type_name -> goginx.control.v1.Proxy
	7, // 2: goginx.control.v1.ProxyListResponse.proxies:type_name -> goginx.control.v1.Proxy
	1, // 3: goginx.control.v1.MuxFrame.type:type_name -> goginx.control.v1.MuxFrameType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_control_controlpb_control_proto_init() }
func file_internal_control_controlpb_control_proto_init() {
	if File_internal_control_controlpb_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_control_controlpb_control_proto_rawDesc), len(file_internal_control_controlpb_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_control_controlpb_control_proto_goTypes,
		DependencyIndexes: file_internal_control_controlpb_control_proto_depIdxs,
		EnumInfos:         file_internal_control_controlpb_control_proto_enumTypes,
		MessageInfos:      file_internal_control_controlpb_control_proto_msgTypes,
	}.Build()
	File_internal_control_controlpb_control_proto = out.File
	file_internal_control_controlpb_control_proto_goTypes = nil
	file_internal_control_controlpb_control_proto_depIdxs = nil
}
